json.id car.id
json.user_id car.user_id
json.make car.make
json.model car.model
json.year car.year
json.color car.color
json.rate car.rate
json.seats car.seats
json.transmission car.transmission
json.image_url car.image_url
